language: python
sudo: required
dist: trusty
python:
    - "2.7"
addons:
    postgresql: "9.4"
services:
    - postgresql
before_install:
    - sudo [ $(ip addr show | grep "inet6 ::1" | wc -l) -lt "1" ] && sudo sed -i '/^::1/d' /etc/hosts && sudo sed -i '/^127.0.1.1/d' /etc/hosts
    - sudo mkdir /etc/dbod
    - sudo mkdir /var/log/dbod
    - sudo chown travis /var/log/dbod
    - sudo cp static/api.cfg /etc/dbod
    - wget https://github.com/begriffs/postgrest/releases/download/v0.3.1.1/postgrest-0.3.1.1-ubuntu.tar.xz
    - tar xf postgrest-0.3.1.1-ubuntu.tar.xz
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - python setup.py install
before_script:
    - psql -c 'CREATE DATABASE dbod;' -U postgres
    - psql -d dbod -f dbod/tests/db_test.sql -U postgres
    - ./postgrest postgres://postgres@localhost/dbod -a postgres -s api &
    - bin/dbod-api &
    - sleep 5
script:
    - curl -g http://localhost:3000
    - nosetests --with-coverage --cover-package=dbod --cover-html -s
after_success:
    coveralls 
